config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :imageposts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "imageposts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :imagepost
end

app/models/imagepost.rb
class Imagepost < ApplicationRecord
  belongs_to :user
  # has_many :image
  mount_uploader :image, ImagepostUploader
  validates :caption, presence: true
  # mount_uploader :image, TweetImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :imagepost_id)
    end
end

app/controllers/imageposts_controller.rb
class ImagepostsController < ApplicationController
  before_action :set_imagepost, only: [:show, :edit, :update, :destroy]

  # GET /imageposts
  # GET /imageposts.json
  def index
    @imageposts = Imagepost.all
  end

  # GET /imageposts/1
  # GET /imageposts/1.json
  def show
  end

  # GET /imageposts/new
  def new
    @imagepost = Imagepost.new
  end

  # GET /imageposts/1/edit
  def edit
  end

  # POST /imageposts
  # POST /imageposts.json
  def create
    @imagepost = Imagepost.new(imagepost_params)
    @imagepost.user = current_user

    respond_to do |format|
      if @imagepost.save
        format.html { redirect_to @imagepost, notice: 'Imagepost was successfully created.' }
        format.json { render :show, status: :created, location: @imagepost }
      else
        format.html { render :new }
        format.json { render json: @imagepost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imageposts/1
  # PATCH/PUT /imageposts/1.json
  def update
    respond_to do |format|
      if @imagepost.update(imagepost_params)
        format.html { redirect_to @imagepost, notice: 'Imagepost was successfully updated.' }
        format.json { render :show, status: :ok, location: @imagepost }
      else
        format.html { render :edit }
        format.json { render json: @imagepost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imageposts/1
  # DELETE /imageposts/1.json
  def destroy
    @imagepost.destroy
    respond_to do |format|
      format.html { redirect_to imageposts_url, notice: 'Imagepost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imagepost
      @imagepost = Imagepost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imagepost_params
      params.require(:imagepost).permit(:image_url, :user_id, :caption, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/imageposts_helper.rb
module ImagepostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :comment_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :imagepost_id %>
    <%= form.text_field :imagepost_id, id: :comment_imagepost_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Imagepost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user %></td>
        <td><%= comment.imagepost %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Imagepost:</strong>
  <%= @comment.imagepost %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/imageposts/_form.html.erb
<%= form_with(model: imagepost, local: true) do |form| %>
  <% if imagepost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imagepost.errors.count, "error") %> prohibited this imagepost from being saved:</h2>

      <ul>
      <% imagepost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :imagepost_image %>
  </div>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :imagepost_user_id %>
  </div> -->

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption, id: :imagepost_caption %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imageposts/edit.html.erb
<h1>Editing Imagepost</h1>

<%= render 'form', imagepost: @imagepost %>

<%= link_to 'Show', @imagepost %> |
<%= link_to 'Back', imageposts_path %>

app/views/imageposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imageposts</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>User</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imageposts.each do |imagepost| %>

      <tr>
        <td><%= image_tag imagepost.image_url(:thumb) %></td>
        <td><%= imagepost.user.email %></td>
        <td><%= imagepost.caption %></td>
        <td><%= link_to 'Show', imagepost %></td>
        <td><%= link_to 'Edit', edit_imagepost_path(imagepost) %></td>
        <td><%= link_to 'Destroy', imagepost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imagepost', new_imagepost_path %>

app/views/imageposts/new.html.erb
<h1>New Imagepost</h1>

<%= render 'form', imagepost: @imagepost %>

<%= link_to 'Back', imageposts_path %>

app/views/imageposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image url:</strong>
  <%= @imagepost.image_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @imagepost.user.name %>
</p>

<p><%= image_tag @imagepost.image_url(:medium) %></p>
<p>
  <strong>Caption:</strong>
  <%= @imagepost.caption %>
</p>

<%= link_to 'Edit', edit_imagepost_path(@imagepost) %> |
<%= link_to 'Back', imageposts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instawam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <p>Logged in as: <%= current_user.name %></p>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
      <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>